import express from "express";
import fetch from "node-fetch";

const router = express.Router();

// POST /api/generate/metadata
// body: { filename: string } (for now minimal)
router.post("/metadata", async (req, res) => {
  const { filename } = req.body;

  // If GEMINI_API_KEY is not set, return mock metadata
  if (!process.env.GEMINI_API_KEY) {
    // Simple mock: derive title/description/keywords from filename
    const base = filename ? filename.replace(/\.[^/.]+$/, "") : "Example Image";
    const title = `${base} - Stock Image`;
    const description = `A high-quality stock image titled ${base}. Generated by CSVnest.`;
    const keywords = base.split(/[-_\s]+/).slice(0, 10).map(k => k.toLowerCase());
    const prompt = `Photo of ${base}, high resolution, product-style, white background`;
    return res.json({ title, description, keywords, prompt });
  }

  // Placeholder for real Gemini integration
  try {
    // Real implementation would call Google Gemini API with filename as context
    // For now, echo back filename
    const title = `${filename} - Generated by Gemini`;
    const description = `Generated description for ${filename}`;
    const keywords = filename ? filename.split(/[-_\s]+/).slice(0,10) : [];
    const prompt = `Generate metadata for ${filename}`;
    return res.json({ title, description, keywords, prompt });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to generate metadata" });
  }
});

export default router;
